package com.example.smartalarm.domain.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalTime

/**
 * Represents an alarm that will adjust based on traffic conditions.
 *
 * @property id Unique identifier for the alarm (auto-generated by Room)
 * @property name User-defined name for the alarm
 * @property isEnabled Whether the alarm is currently active
 * @property targetArrivalTime The time the user wants to arrive at their destination
 * @property travelBufferMinutes Additional buffer time to add to the travel time (in minutes)
 * @property destinationAddress The destination address for traffic calculation
 * @property destinationLat Latitude of the destination (optional, can be set later)
 * @property destinationLng Longitude of the destination (optional, can be set later)
 * @property lastCalculatedDepartureTime The last calculated time to depart based on traffic
 * @property isRecurring Whether the alarm repeats on specific days
 * @property daysOfWeek Set of days (1-7, where 1 is Sunday) when the alarm should be active
 * @property isVibrate Whether the alarm should vibrate
 * @property ringtoneUri URI of the ringtone to play
 * @property volume Volume level (0.0 to 1.0)
 * @property isIncreasingVolume Whether the volume should gradually increase
 * @property createdTimestamp When the alarm was created
 * @property updatedTimestamp When the alarm was last updated
 */
@Entity(tableName = "alarms")
data class Alarm(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String,
    val isEnabled: Boolean = true,
    val targetArrivalTime: LocalTime,
    val travelBufferMinutes: Int = 15,
    val destinationAddress: String,
    val destinationLat: Double? = null,
    val destinationLng: Double? = null,
    val lastCalculatedDepartureTime: LocalTime? = null,
    val isRecurring: Boolean = false,
    val daysOfWeek: Set<Int> = emptySet(),
    val isVibrate: Boolean = true,
    val ringtoneUri: String = "",
    val volume: Float = 0.8f,
    val isIncreasingVolume: Boolean = true,
    val createdTimestamp: Long = System.currentTimeMillis(),
    val updatedTimestamp: Long = System.currentTimeMillis()
) {
    /**
     * Returns the next occurrence of the alarm time from the given time.
     * If the alarm is not recurring, returns the next occurrence of the target time.
     * If the alarm is recurring, returns the next occurrence based on the selected days.
     */
    fun getNextAlarmTime(fromTime: java.time.LocalDateTime = java.time.LocalDateTime.now()): java.time.LocalDateTime {
        val timePart = targetArrivalTime
        var nextDateTime = fromTime.toLocalDate().atTime(timePart)
        
        // If the time has already passed today, move to next day
        if (nextDateTime.isBefore(fromTime)) {
            nextDateTime = nextDateTime.plusDays(1)
        }
        
        if (!isRecurring) {
            return nextDateTime
        }
        
        // For recurring alarms, find the next matching day of week
        while (nextDateTime.dayOfWeek.value !in daysOfWeek) {
            nextDateTime = nextDateTime.plusDays(1)
        }
        
        return nextDateTime
    }
    
    /**
     * Returns true if the alarm should be active on the given day of week.
     * @param dayOfWeek 1-7 where 1 is Sunday
     */
    fun isActiveOnDay(dayOfWeek: Int): Boolean {
        return !isRecurring || dayOfWeek in daysOfWeek
    }
    
    /**
     * Creates a copy of the alarm with the specified enabled state.
     */
    fun copyWithEnabled(enabled: Boolean): Alarm {
        return this.copy(isEnabled = enabled, updatedTimestamp = System.currentTimeMillis())
    }
}
